//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class predmet
    {
        public string Naziv_predmeta { get; set; }
        public string Sifru_predmeta { get; set; }
        public string Kratak_opis { get; set; }
        public Nullable<bool> Labaratoriske_vezbe { get; set; }
        public Nullable<sbyte> Godina { get; set; }
        public int id { get; set; }
    }
}
