//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        public string Ime { get; set; }
        public string Srednje_ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> datum_rodjenja { get; set; }
        public Nullable<System.DateTime> datum_postavljanja { get; set; }
        public string naziv_predmeta { get; set; }
        public int id { get; set; }
    }
}
