//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class slusa
    {
        public string naziv_predmeta { get; set; }
        public int br_indexa { get; set; }
    }
}
